import { readFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MEMBERS_DIR = join(__dirname, '..', 'members');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO = process.env.GITHUB_REPO ?? 'imti-ahmed/The-Misfits';
const GITHUB_BASE = process.env.GITHUB_BASE_BRANCH ?? 'main';
const GUILD_ORIGIN = process.env.GUILD_ORIGIN ?? 'the-misfits.vercel.app';

// ── GitHub helpers ────────────────────────────────────────────────────────────

async function gh(path, options = {}) {
  return fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...(options.headers ?? {}),
    },
  });
}

async function getBaseSha() {
  const res = await gh(`/repos/${GITHUB_REPO}/git/refs/heads/${GITHUB_BASE}`);
  const data = await res.json();
  return data.object.sha;
}

async function createBranch(branch, sha) {
  const res = await gh(`/repos/${GITHUB_REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
  });
  if (!res.ok) {
    const err = await res.json();
    if (!err.message?.includes('already exists')) {
      throw new Error(`Branch creation failed: ${err.message}`);
    }
  }
}

async function getFileSha(filePath, ref) {
  const res = await gh(`/repos/${GITHUB_REPO}/contents/${filePath}?ref=${ref}`);
  if (!res.ok) return null;
  const data = await res.json();
  return data.sha;
}

async function deleteFile(branch, filePath, sha, message) {
  const res = await gh(`/repos/${GITHUB_REPO}/contents/${filePath}`, {
    method: 'DELETE',
    body: JSON.stringify({ message, sha, branch }),
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`File deletion failed: ${err.message}`);
  }
}

async function openPR(branch, title, body) {
  // Check if a PR already exists for this branch to avoid duplicates
  const existing = await gh(`/repos/${GITHUB_REPO}/pulls?head=${GITHUB_REPO.split('/')[0]}:${branch}&state=open`);
  if (existing.ok) {
    const list = await existing.json();
    if (list.length > 0) return list[0].html_url;
  }

  const res = await gh(`/repos/${GITHUB_REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({ title, body, head: branch, base: GITHUB_BASE }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(`PR creation failed: ${data.message}`);
  return data.html_url;
}

// ── Site checks ───────────────────────────────────────────────────────────────

async function checkSiteStatus(url) {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 10_000);
    const res = await fetch(url, {
      method: 'GET',
      signal: controller.signal,
      redirect: 'follow',
      headers: { 'User-Agent': 'TheMisfits-HealthCheck/1.0' },
    });
    clearTimeout(timer);
    return { active: res.status < 400, status: res.status };
  } catch {
    return { active: false, status: null };
  }
}

async function checkWidgetPresence(url) {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 15_000);
    const res = await fetch(url, {
      method: 'GET',
      signal: controller.signal,
      redirect: 'follow',
      headers: { 'User-Agent': 'TheMisfits-HealthCheck/1.0' },
    });
    clearTimeout(timer);
    if (!res.ok) return false;
    const html = await res.text();
    return html.toLowerCase().includes(GUILD_ORIGIN.toLowerCase());
  } catch {
    return false;
  }
}

// ── PR body ───────────────────────────────────────────────────────────────────

function buildRemovalPRBody(member, siteStatus, widgetPresent) {
  const issues = [];
  if (!siteStatus.active) {
    const statusStr = siteStatus.status ? `HTTP ${siteStatus.status}` : 'unreachable (timeout)';
    issues.push(`- **Site is down** — \`${member.url}\` returned ${statusStr}`);
  }
  if (!widgetPresent) {
    issues.push(`- **Widget not detected** — no guild widget found on their homepage`);
  }

  return [
    `## Member Health Check — Removal Proposal`,
    ``,
    `This PR was auto-generated by the member health check workflow.`,
    ``,
    `### Member`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| **Name** | ${member.name || '—'} |`,
    `| **Nickname** | ${member.nickname || '—'} |`,
    `| **Site** | [${member.url}](${member.url}) |`,
    `| **Email** | ${member.email || '—'} |`,
    `| **Slug** | \`${member.slug}\` |`,
    ``,
    `### Issues Found`,
    ``,
    ...issues,
    ``,
    `### Action`,
    ``,
    `- **Merge this PR** → member is removed from the webring`,
    `- **Close this PR** → reach out to them first at ${member.email || '(no email on file)'}`,
    ``,
    `---`,
    `*Auto-generated by The Misfits health check · ${new Date().toISOString().split('T')[0]}*`,
  ].join('\n');
}

// ── Main ──────────────────────────────────────────────────────────────────────

const DRY_RUN = process.env.DRY_RUN === 'true';
const MEMBER_SLUG = process.env.MEMBER_SLUG ?? null;

async function main() {
  if (!DRY_RUN && !GITHUB_TOKEN) {
    console.error('GITHUB_TOKEN is not set');
    process.exit(1);
  }

  let files = readdirSync(MEMBERS_DIR).filter(f => f.endsWith('.md')).sort();
  if (MEMBER_SLUG) files = files.filter(f => f === `${MEMBER_SLUG}.md`);

  const members = files.map(filename => {
    const slug = filename.replace(/\.md$/, '');
    const raw = readFileSync(join(MEMBERS_DIR, filename), 'utf-8');
    const { data } = matter(raw);
    return { slug, ...data };
  });

  console.log(`Checking ${members.length} member(s)...\n`);

  const flagged = [];

  for (const member of members) {
    if (!member.url) {
      console.log(`[skip] ${member.slug} — no URL`);
      continue;
    }

    process.stdout.write(`[check] ${member.slug} (${member.url})\n`);

    const siteStatus = await checkSiteStatus(member.url);
    console.log(`  site: ${siteStatus.active ? 'active' : 'DOWN'} (${siteStatus.status ?? 'timeout'})`);

    let widgetPresent = false;
    if (siteStatus.active) {
      widgetPresent = await checkWidgetPresence(member.url);
      console.log(`  widget: ${widgetPresent ? 'found' : 'MISSING'}`);
    } else {
      console.log(`  widget: skipped (site unreachable)`);
    }

    if (!siteStatus.active || !widgetPresent) {
      console.log(`  → flagged`);
      flagged.push({ member, siteStatus, widgetPresent });
    } else {
      console.log(`  → OK`);
    }
  }

  console.log(`\n${flagged.length} member(s) flagged.`);

  if (flagged.length === 0) return;

  if (DRY_RUN) {
    console.log('\n[DRY RUN] Skipping branch + PR creation.');
    return;
  }

  console.log('\nCreating removal PRs...\n');
  const baseSha = await getBaseSha();
  const today = new Date().toISOString().split('T')[0].replace(/-/g, '');

  for (const { member, siteStatus, widgetPresent } of flagged) {
    const branch = `removal/${member.slug}-${today}`;
    try {
      await createBranch(branch, baseSha);

      const fileSha = await getFileSha(`members/${member.slug}.md`, GITHUB_BASE);
      if (!fileSha) throw new Error('Could not get SHA for members/' + member.slug + '.md');

      await deleteFile(
        branch,
        `members/${member.slug}.md`,
        fileSha,
        `Remove member: ${member.nickname || member.slug}`
      );

      const prBody = buildRemovalPRBody(member, siteStatus, widgetPresent);
      const prUrl = await openPR(
        branch,
        `Remove member: ${member.nickname || member.slug}`,
        prBody
      );

      console.log(`[done] ${member.slug} → ${prUrl}`);
    } catch (err) {
      console.error(`[fail] ${member.slug}: ${err.message}`);
    }
  }
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
