name: Delete Merged Branch

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'member/') || startsWith(github.event.pull_request.head.ref, 'removal/'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete branch
        run: gh api repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} -X DELETE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
